package com.voicify.voicify_assistant_sdk.assistantDrawerUITypes

import java.io.Serializable

data class BodyProps(
    //val height: String? = null,
    val backgroundColor: String? = null,
    val assistantImageBorderColor: String? = null,
    val assistantImageBorderWidth: Int? = null,
    //val assistantImageBorderStyle: String? = null,
    val assistantImageBorderRadius: Float? = null,
    val assistantImage: String? = null,
    val messageSentTextColor: String? = null,
    val messageSentBackgroundColor: String? = null,
    val messageReceivedFontSize: Float? = null,
    val messageReceivedTextColor: String? = null,
    val messageReceivedBackgroundColor: String? = null,
    val messageSentFontSize: Float? = null,
    val messageSentBorderWidth: Int? = null,
    //val messageSentBorderStyle: String? = null,
    val messageSentBorderColor: String? = null,
    val messageReceivedBorderWidth: Int? = null,
    //val messageReceivedBorderStyle: String? = null,
    val messageReceivedBorderColor: String? = null,
    val messageSentBorderTopLeftRadius: Float? = null,
    val messageSentBorderTopRightRadius: Float? = null,
    val messageSentBorderBottomLeftRadius: Float? = null,
    val messageSentBorderBottomRightRadius: Float? = null,
    val messageReceivedBorderTopLeftRadius: Float? = null,
    val messageReceivedBorderTopRightRadius: Float? = null,
    val messageReceivedBorderBottomLeftRadius: Float? = null,
    val messageReceivedBorderBottomRightRadius: Float? = null,
    val paddingLeft: Int? = null,
    val paddingRight: Int? = null,
    val paddingTop: Int? = null,
    val paddingBottom: Int? = null,
//    val borderTopColor: String? = null,
//    val borderBottomColor: String? = null,
    val borderColor: String? = null,
    val hintsTextColor: String? = null,
    val hintsFontSize: Float? = null,
    val hintsPaddingTop: Int? = null,
    val hintsPaddingBottom: Int? = null,
    val hintsPaddingRight: Int? = null,
    val hintsPaddingLeft: Int? = null,
    val hintsBackgroundColor: String? = null,
    val hintsBorderWidth: Int? = null,
    val hintsBorderColor: String? = null,
    //val hintsBorderStyle: String? = null,
    val hintsBorderRadius: Float? = null,
) : Serializable
